In [1]:

import os
import pandas as pd
#df1 = pd.read_csv(r'刘玲霞3.csv',encoding="utf-8")
from pandasgui import show
import pandas as pd
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

C:\Users\hnsj\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [8]:
#df1 = pd.read_excel(r"‪D:\2024财政一体化\一卡通发放记录\补贴资金到户明细表.xlsx",sheet_name="Sheet0")

# 修正路径
file_path = r"D:\2024财政一体化\一卡通发放记录\补贴资金到户明细表.xlsx"

# 读取 Excel 文件
df1 = pd.read_excel(file_path, sheet_name="Sheet0")

In [11]:
file_path = r"D:\2024财政一体化\一卡通发放记录\补贴资金到户明细表.xlsx"

# 读取 Excel 文件
df2 = pd.read_excel(file_path, sheet_name="Sheet1")

In [51]:
df4 = pd.read_csv(r'D:\2024财政一体化\一卡通发放记录\农户一卡通2023.csv')

C:\Users\hnsj\AppData\Local\Temp\ipykernel_20968\2033932118.py:1: DtypeWarning:

Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.

In [52]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1297481 entries, 0 to 1297480
Data columns (total 13 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1297481 non-null  int64
 1   序号          1297481 non-null  int64
 2   对象代码        1297481 non-null  int64
 3   对象姓名        1297481 non-null  object
 4   身份证号码       1297481 non-null  object
 5   发放账号        1297481 non-null  object
 6   补贴类型        1297481 non-null  object
 7   摘要          1297481 non-null  object
 8   补贴金额        1297481 non-null  float64
 9   家庭地址        1295982 non-null  object
 10  登记日期        1297481 non-null  object
 11  发放日期        1297481 non-null  object
 12  备注          239263 non-null   object
dtypes: float64(1), int64(3), object(9)
memory usage: 128.7+ MB

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496853 entries, 0 to 496852
Data columns (total 12 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   序号      496853 non-null  int64
 1   对象代码    496853 non-null  int64
 2   对象姓名    496853 non-null  object
 3   身份证号码   496853 non-null  object
 4   发放账号    496853 non-null  object
 5   补贴类型    496853 non-null  object
 6   摘要      496853 non-null  object
 7   补贴金额    496853 non-null  float64
 8   家庭地址    495939 non-null  object
 9   登记日期    496853 non-null  object
 10  发放日期    496853 non-null  object
 11  备注      82415 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 45.5+ MB

In [28]:
#df3 = pd.merge(df1, df2, on='A', how='left')
#除了 left 之外，pandas.merge() 函数的 how 参数还可以取以下值：

#'inner': 内连接，仅返回两个表中都存在的记录。
#'right': 右连接，返回右表中的所有记录，以及左表中连接键匹配的记录。
#'outer': 外连接，返回两个表中的所有记录，以及连接键匹配的记录。
df3 = pd.merge(df1,df2, left_on='企业名称', right_on='收款人全称', how='inner', indicator=True)

In [17]:
#df = df1.merge(df2, on='借款人', how='outer',sort=False)
#cust.merge(purc, on='id')
#df = pd.concat(all_df,sort = False)
df = pd.concat([df1,df2],sort = False)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1496853 entries, 0 to 496852
Data columns (total 12 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   序号      1496853 non-null  int64
 1   对象代码    1496853 non-null  int64
 2   对象姓名    1496853 non-null  object
 3   身份证号码   1496853 non-null  object
 4   发放账号    1496853 non-null  object
 5   补贴类型    1496853 non-null  object
 6   摘要      1496853 non-null  object
 7   补贴金额    1496853 non-null  float64
 8   家庭地址    1495174 non-null  object
 9   登记日期    1496853 non-null  object
 10  发放日期    1496853 non-null  object
 11  备注      275208 non-null   object
dtypes: float64(1), int64(2), object(9)
memory usage: 148.5+ MB

In [33]:
jg = df[df['死亡注销业务时间'].notna()]

In [37]:
jg.head(0)

Empty DataFrame
Columns: [Unnamed: 0, 序号_x, 对象代码, 补贴类型, 对象姓名, 身份证号码, 发放账号, 实发金额, 发放日期, 家庭地址, 手机号码, 死亡注销业务时间, 应发金额, 行政区划编码, 区划类别, 行政主管部门编码, 行政主管部门名称, 单位显示编码, 单位名称, 单位性质, 经费供给方式, 单位类别类, 单位类别款, 单位类别, 人员支出类类, 人员支出类款, 人员支出类, 是否为垂直管理单位, 序号_y, 姓名, 性别, 人员类别, 在职教职工类型, 在职人员来源, 人员身份, 职务（职称）, 是否为少数民族, 是否财政统发工资, 学历, 隶属处（科）室, 出生日期, 参加工作时间, 工龄, 离退时间, 基本工资(元/月), 基本离休费(元/月), 基本退休费(元/月), 基本退职费(元/月), 国家规定津补贴(元/月), 地方出台津补贴(元/月), 实际执行月工资(元/月), 调动备注, 减少原因, 人员状态, 操作状态]
Index: []

[0 rows x 55 columns]

In [21]:
df['对象代码'] = df['对象代码'].astype('str')
df['身份证号码'] = df['身份证号码'].astype('str')
df['发放账号'] = df['发放账号'].astype('str')

In [22]:
df.to_csv(r'D:\2024财政一体化\一卡通发放记录\农户一卡通公职人员比对.csv',encoding="utf-8-sig")

In [49]:
dfyear.to_csv(r'D:\2024财政一体化\一卡通发放记录\农户一卡通2023.csv',encoding="utf-8-sig")

In [50]:
dfyear.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1297481 entries, 0 to 496850
Data columns (total 12 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   序号      1297481 non-null  int64
 1   对象代码    1297481 non-null  object
 2   对象姓名    1297481 non-null  object
 3   身份证号码   1297481 non-null  object
 4   发放账号    1297481 non-null  object
 5   补贴类型    1297481 non-null  object
 6   摘要      1297481 non-null  object
 7   补贴金额    1297481 non-null  float64
 8   家庭地址    1295982 non-null  object
 9   登记日期    1297481 non-null  object
 10  发放日期    1297481 non-null  datetime64[ns]
 11  备注      239263 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(9)
memory usage: 128.7+ MB

In [23]:
show(df.head(1111))

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [24]:
df.columns

Index(['序号', '对象代码', '对象姓名', '身份证号码', '发放账号', '补贴类型', '摘要', '补贴金额', '家庭地址',
       '登记日期', '发放日期', '备注'],
      dtype='object')

In [25]:
df['身份证号码']=df['身份证号码'].str.strip()
df['补贴类型']=df['补贴类型'].str.strip()
df['发放账号']=df['发放账号'].str.strip()

In [29]:
fenzu = df.groupby('补贴类型')['补贴金额'].sum()

In [32]:
fenzu1 = df.groupby('补贴类型')['补贴金额'].agg(['sum', 'count'])

In [53]:
fenzu2 = df4.groupby('补贴类型',as_index=False)['补贴金额'].agg(['sum', 'count','min','max','mean']).reset_index()

In [54]:
show(fenzu2)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [56]:
#关键字搜索__模糊匹配
filtered_df = df4[df4['补贴类型'].str.contains('高龄津贴', regex=True, case=False)]
show(filtered_df)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [48]:
# 假设 df 是你的 DataFrame，date_column 是日期列的名称
# 假设你想要筛选 2024 年 1 月 1 日到 2024 年 1 月 31 日之间的数据

start_date = '2023-01-01'
end_date = '2023-12-31'

# 将日期列转换为日期时间类型
df['发放日期'] = pd.to_datetime(df['发放日期'])

# 使用布尔索引筛选日期范围内的数据
dfyear = df[(df['发放日期'] >= start_date) & (df['发放日期'] <= end_date)]

In [29]:
df3.to_excel(r'D:\2024财政一体化\衡南县工商登记信息\多企业财政支付记录_联系电话为主键.xlsx',encoding = "utf-8")

In [7]:
merged_df.to_excel(r'自来水厂工资合并2.xlsx')

In [6]:
import pandas as pd

# 读取Excel文件并将所有表格存储在一个字典中
excel_file = pd.ExcelFile(r'D:\新建文件夹\2020.1-2022.12工资(1).xlsx')
dfs = {}

for sheet_name in excel_file.sheet_names:
    df = excel_file.parse(sheet_name)
    # 添加一列以记录sheet_name
    df['Sheet Name'] = sheet_name
    dfs[sheet_name] = df

# 使用 pd.concat() 合并所有表格
merged_df = pd.concat(dfs.values(), ignore_index=True)

# 输出合并后的DataFrame
print(merged_df)

       序号      姓名      岗位工资      薪级工资   加班工资   信访补助    手机补贴  营业部奖      应发工资  \
0       1     廖伟国    3540.0      1830    NaN  235.0     NaN   NaN    5605.0
1       2     张少清    3320.0      1723    NaN    NaN     NaN   NaN    5043.0
2       3     陈运生    3698.0      1723  400.0    NaN     NaN   NaN    5821.0
3       4     贺小银    2976.0      1723    NaN  235.0     NaN   NaN    4934.0
4       5     彭忠美    2746.0      1723    NaN    NaN     NaN   NaN    4469.0
...   ...     ...       ...       ...    ...    ...     ...   ...       ...
2899   79     胡春梅    1234.0       NaN    NaN    NaN     NaN   NaN    1234.0
2900   80     屈永红    1356.0       NaN    NaN    NaN     NaN   NaN    1356.0
2901   81     李丽华    1356.0       NaN    NaN    NaN     NaN   NaN    1356.0
2902   合计     NaN  223127.0  113155.0    NaN  470.0  1020.0   NaN  396874.0
2903  NaN  制表:罗兰兰       NaN       NaN    NaN    NaN     NaN   NaN       NaN

       扣款  ... 扣节假日值班费  扣医保     误餐补助 工会补贴 加工资       车补  普调 扣2022工会经费 新扣社保  \
0     NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
1     NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
2     NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
3     NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
4     NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
...   ...  ...     ...  ...      ...  ...  ..      ...  ..       ...  ...
2899  NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
2900  NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
2901  NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN
2902  0.0  ...     NaN  0.0  23237.0  NaN NaN  34695.0 NaN       NaN  NaN
2903  NaN  ...     NaN  NaN      NaN  NaN NaN      NaN NaN       NaN  NaN

      补扣1-10月
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
...       ...
2899      NaN
2900      NaN
2901      NaN
2902      NaN
2903      NaN

[2904 rows x 33 columns]

In [15]:
#df1 = pd.read_excel(r'D:\OneDrive\---------待办-----\何志军\衡南县2023年严重精神障碍患者救治救助监护奖励名单(1).xlsx')
df1 = pd.read_excel(r'D:\OneDrive\---------待办-----\何志军\南乡_高血压管理_名单.xlsx')
    
#df3 = pd.merge(df1, df2, on='A', how='left')
#除了 left 之外，pandas.merge() 函数的 how 参数还可以取以下值：

#'inner': 内连接，仅返回两个表中都存在的记录。
#'right': 右连接，返回右表中的所有记录，以及左表中连接键匹配的记录。
#'outer': 外连接，返回两个表中的所有记录，以及连接键匹配的记录。
#df3 = pd.merge(df1,df2, left_on='企业名称', right_on='收款人全称', how='inner', indicator=True)

In [9]:
df2 = pd.read_excel(r'C:\Users\hnsj\Desktop\衡南县_老年死亡收集_1.xlsx')

In [16]:
df1.head()

   序号 对象姓名                身份证号               发放账号 应发补贴金额 实发补贴金额
0   1  刘邦桃  430422194202093574  81011450011828596  2400元  2400元
1   2  罗维禄  430422195009200037  81011450011913980  2400元  2400元
2   3  谢树柏  430422196011023572  81011450011830037  2400元  2400元
3   4  谭芳林  430422198302243857  81011450048047371  2400元  2400元
4   5  石爱梅  430422197001073861  81011450048046446  2400元  2400元

In [17]:
df2.head()

,序号,报告县（市）区,死者姓名,身份证号码,别,死亡年龄（岁）,职业,文化程度,死亡日期 （年/月/日）,死亡地点,死亡原因（尽量填写）,生前主要基础疾患（填名称。若无，不填),联系人电话,报告日期 （年/月/日）
0,1,衡南县,包中实,430422194410116013,男,79,4,4,2023-01-01,3,脑梗死,脑梗死,18942014989,2023-01-01
1,2,衡南县,曹敦贵,430422194005197710,男,82,4,3,2022-12-28,3,慢阻肺,慢阻肺,13076075500,2023-01-11
2,3,衡南县,曹家传,430422192812056413,男,94,4,4,2022-12-25,3,左心力衰竭,高血压,18711479302,2023-01-05
3,4,衡南县,曹少兰,430422194012269022,女,82,4,3,2023-01-01,3,高血压,高血压,18473462006,2023-01-04
4,5,衡南县,曹时宏,430422195609041770,男,66,4,3,2022-12-23,3,肺气肿,肺气肿,15773463900,2023-01-01

In [18]:
df3 = pd.merge(df1, df2, left_on='身份证号', right_on='身份证号码', how='inner')
print(df3)

   序号_x 对象姓名                身份证号               发放账号 应发补贴金额 实发补贴金额  序号_y  \
0   354  封木云  430422193603011774  81011450012963022  2400元  2400元   116

  报告县（市）区 死者姓名               身份证号码  别  死亡年龄（岁）  职业  文化程度 死亡日期 （年/月/日）  死亡地点  \
0     衡南县  封木云  430422193603011774  男       86   4     3   2022-12-04     3

  死亡原因（尽量填写） 生前主要基础疾患（填名称。若无，不填)        联系人电话 报告日期 （年/月/日）
0         慢支                  慢支  15773463900   2023-01-01

In [19]:
show(df3)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

In [7]:
import pandas as pd
import pyodbc

# 创建数据库连接
server = 'DESKTOP-AKFURTF'
database = '惠农补贴2015_2022'
username = 'sa'
password = '1'
cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+password)

# 执行SQL查询
sql = "SELECT * FROM [工资信息数据2022$]"  # 你需要替换为你的表名
df2 = pd.read_sql(sql, cnxn)

# 查看数据
df2.head()

C:\Users\hnsj\anaconda3\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,来源工作簿名称,单位编码,单位名称,姓名,人员编码,身份证,业务年度,月份,基本工资,岗位工资,...,医疗费统筹,住房公积基金,代扣,职业年金,失业保险,大病医疗互助费,民兵训练费,扣发小计,实发工资,工资类别
0,工资信息数据导出(1-22)_1_(1_10).xls,101001,中共衡南县县委会,唐向东,00018,430404197105171519,2022,12,0,0,...,0,0,0,0,0,0,40,40,4986,1
1,工资信息数据导出(1-22)_1_(1_10).xls,101001,中共衡南县县委会,阳华建,00019,430404196504221531,2022,12,0,0,...,0,0,0,0,0,0,40,40,5508,1
2,工资信息数据导出(1-22)_1_(1_10).xls,101001,中共衡南县县委会,陈书坤,00023,430404196302111537,2022,12,0,0,...,0,0,0,0,0,0,40,40,5643,1
3,工资信息数据导出(1-22)_1_(1_10).xls,101001,中共衡南县县委会,刘桂华,00035,430407197008130044,2022,12,0,0,...,0,0,0,0,0,0,40,40,5543,1
4,工资信息数据导出(1-22)_1_(1_10).xls,101001,中共衡南县县委会,阳友,00047,430404197508231512,2022,12,0,0,...,0,0,0,0,0,0,40,40,3441,1

In [8]:
cnxn.colse()#关闭数据库连接

AttributeError: 'pyodbc.Connection' object has no attribute 'colse'